Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -23,11 +23,15 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: "3.12"
-    - name: Install dependencies
+    - name: Install
       run: |
         python -m pip install --upgrade pip
         python -m pip install --upgrade robotpy certifi
         python -m robotpy sync --use-certifi
     - name: Test
       run: |
-        python -m robotpy test --builtin
+        if ! python -m robotpy test --builtin; then
+          echo "Tests failed."
+          exit 1
+        fi
+        "Tests succeeded."
